import type { PortfolioContent } from '../types';

export const es: PortfolioContent = {
  nav: {
    name: 'Luis De La Torre',
    role: 'Senior Full-Stack & Mobile',
    links: [
      { label: 'Servicios', anchor: 'services' },
      { label: 'Experiencia', anchor: 'experience' },
      { label: 'Proyectos', anchor: 'projects' },
    ],
    languageToggleLabel: 'ES / en',
    cta: { label: 'Trabajemos', anchor: 'contact' },
  },
  hero: {
    availability: 'Disponible para proyectos freelance',
    titleLead: 'Construyo productos digitales que generan',
    titleAccent: 'impacto real.',
    subtitle:
      'Senior Full-Stack & Mobile Developer con +7 años diseñando apps móviles, plataformas web escalables, experiencias de Realidad Aumentada y sistemas distribuidos. De la arquitectura al despliegue en App Store y Google Play.',
    primaryCta: { label: 'Hablemos de tu proyecto', anchor: 'contact' },
    secondaryCta: { label: 'Ver proyectos', anchor: 'projects' },
    stats: [
      { value: '7+', label: 'años de experiencia' },
      { value: '15+', label: 'microservicios en producción' },
      { value: '99.9%', label: 'uptime sostenido' },
    ],
    cvLabel: 'Descargar CV',
    cvUrl: '/cv.pdf',
    clientsHeading: 'Empresas y sectores donde he entregado',
    clients: ['Banca · Produbanco', 'E-commerce · Acid Labs', 'IoT · Audax', 'Telecom · Smartisp', 'Salud · HL7/FHIR', 'AR/VR · Unity'],
  },
  services: {
    kicker: 'servicios',
    heading: 'Cómo puedo ayudarte',
    items: [
      { index: '01', tag: 'WEB', title: 'Desarrollo Web', description: 'Aplicaciones React y Next.js de alto rendimiento, dashboards en tiempo real y SPAs escalables con UX pulida.' },
      { index: '02', tag: 'MOBILE', title: 'Apps Móviles', description: 'iOS y Android nativo (Swift/Kotlin) y multiplataforma con Flutter, KMP y React Native, publicadas en las stores.' },
      { index: '03', tag: 'AR/3D', title: 'Realidad Aumentada & Unity', description: 'Experiencias AR nativas (ARKit/ARCore) y 3D/VR con Unity que digitalizan productos y triplican el engagement.' },
      { index: '04', tag: 'BACKEND', title: 'Backend & Microservicios', description: 'Arquitecturas distribuidas, DDD, event-driven y APIs robustas con NestJS, FastAPI, Spring Boot y Go.' },
      { index: '05', tag: 'CLOUD', title: 'Cloud & DevOps', description: 'Infraestructura en AWS y Azure con Terraform (IaC), CI/CD, Docker y Kubernetes para despliegues confiables.' },
      { index: '06', tag: 'AI/ML', title: 'Integración de IA/ML', description: 'Pipelines de datos, análisis predictivo y modelos de machine learning integrados directamente en tu producto.' },
      { index: '07', tag: 'LEAD', title: 'Consultoría & Tech Lead', description: 'Definición de arquitectura, estándares de ingeniería y liderazgo técnico para llevar tu producto a producción.' },
      { index: '08', tag: 'CHATBOT', title: 'Chatbots con IA', description: 'Asistentes conversacionales automatizados con lenguaje natural (LLMs) para soporte, ventas y atención 24/7, integrados a WhatsApp, web y tus sistemas.' },
      { index: '09', tag: 'AGENTES', title: 'Agentes inteligentes', description: 'Agentes de IA autónomos que razonan, usan herramientas y APIs, y ejecutan tareas de varios pasos para automatizar flujos de trabajo completos.' },
    ],
  },
  process: {
    kicker: 'cómo trabajo',
    heading: 'Un proceso claro, sin sorpresas',
    steps: [
      { number: '01', title: 'Descubrimiento', description: 'Entiendo tu objetivo de negocio, usuarios y restricciones. Definimos alcance, entregables y métricas de éxito.' },
      { number: '02', title: 'Arquitectura', description: 'Diseño la solución técnica: stack, infraestructura y plan de entrega por fases, con estimaciones realistas.' },
      { number: '03', title: 'Desarrollo', description: 'Construyo en iteraciones con demos frecuentes. Código limpio, testeado y con CI/CD desde el día uno.' },
      { number: '04', title: 'Entrega & soporte', description: 'Despliegue a producción (stores/cloud), documentación y acompañamiento post-lanzamiento.' },
    ],
  },
  impact: {
    kicker: 'impacto',
    heading: 'Resultados medibles',
    items: [
      { value: '3×', label: 'más engagement con experiencias AR' },
      { value: '85%', label: 'precisión en detección de emociones (ML)' },
      { value: '40%', label: 'menos tiempo de despliegue' },
      { value: '99.9%', label: 'uptime en producción' },
      { value: '6h→15m', label: 'build de iOS optimizado con CI/CD' },
      { value: '1000+', label: 'usuarios concurrentes escalados' },
      { value: '+20%', label: 'ingresos empresariales generados' },
      { value: '−45%', label: 'response time tras optimización' },
    ],
  },
  stack: {
    kicker: 'stack',
    heading: 'Tecnologías que domino',
    groups: [
      { category: 'Frontend', items: ['React', 'Next.js', 'TypeScript', 'Material UI', 'Angular'] },
      { category: 'Mobile', items: ['Swift', 'Kotlin', 'Flutter', 'KMP', 'React Native'] },
      { category: 'AR / 3D', items: ['Unity', 'ARKit', 'ARCore', 'VR'] },
      { category: 'Backend', items: ['NestJS', 'FastAPI', 'Django', 'Spring Boot', 'Go', 'Node.js'] },
      { category: 'Cloud & DevOps', items: ['AWS', 'Azure', 'Terraform', 'Docker', 'Kubernetes', 'CI/CD'] },
      { category: 'Data & IA', items: ['PostgreSQL', 'MongoDB', 'MySQL', 'Redis', 'Python', 'ML'] },
      { category: 'Arquitectura', items: ['Microservicios', 'DDD', 'Event Sourcing', 'API Gateway'] },
    ],
  },
  experience: {
    kicker: 'trayectoria',
    heading: 'Experiencia',
    items: [
      { period: '06/2025 — 06/2026', location: 'Ecuador', current: true, currentLabel: 'ACTUAL', role: 'Senior Full-Stack Developer', company: 'TechDelivery', description: 'Tech Lead provisional en apps React Native + microservicios en Go (IoT Tuya). Estructuré infraestructura AWS con Terraform y rediseñé los pipelines de despliegue móvil (APK / TestFlight).' },
      { period: '03/2025 — 04/2026', location: 'Quito', role: 'Software Development Engineer', company: 'Netby IT Consulting', description: 'App bancaria (Produbanco) en Kotlin Multiplatform con OTP y biometría facial. Reduje el build de iOS de ~6 horas a 15 minutos con CI/CD en Azure e integré SDKs nativos de terceros.' },
      { period: '09/2022 — 03/2025', location: 'Chile', role: 'Software Development Engineer', company: 'Acid Labs', description: 'Diseñé 15+ microservicios para e-commerce enterprise. Escalé a 1000+ usuarios concurrentes, reduje la latencia 35% y elevé el uptime a 99.9% con CI/CD e IaC en AWS.' },
      { period: '07/2024 — 05/2025', location: 'Quito', role: 'Senior Full-Stack Developer', company: 'Smartisp · Freelance', description: 'Dashboards React en tiempo real para telecom (OLT/ONU) monitoreando 100+ dispositivos con refresco cada 5s vía protocolos industriales (SNMP).' },
      { period: '11/2021 — 07/2022', location: 'Quito', role: 'Senior Full-Stack Developer', company: 'Mushroomsoft', description: 'Plataforma de salud digital con conectores HL7/FHIR sobre AWS. Reduje el response time 45% y elevé la satisfacción de usuarios 20%.' },
      { period: '11/2020 — 12/2021', location: 'Colombia', role: 'Senior Full-Stack Developer', company: 'Sinergia Red Internacional', description: 'Apps React Native multiplataforma y arquitectura backend escalable. Entregué 4+ proyectos clave ~15% antes del deadline con metodología ágil.' },
      { period: '09/2019 — 03/2021', location: 'México', role: 'Full-Stack Developer', company: 'EXCITED, Inc', description: 'Plataforma social con ML (IBM Watson, 85% accuracy en sentiment analysis), messaging en tiempo real y arquitectura event-driven sobre AWS.' },
      { period: '04/2019 — 08/2019', location: 'Ecuador', role: 'Senior Full-Stack Developer', company: 'Vinary VR/AR', description: 'Experiencias AR/VR nativas con Unity que reemplazaron material físico, elevaron el engagement 3× y generaron +20% de ingresos empresariales.' },
    ],
  },
  globalReach: {
    kicker: 'alcance global',
    heading: 'Experiencia nacional e internacional',
    blurb: 'He colaborado con equipos locales y distribuidos en distintos países, culturas y zonas horarias, comunicándome con fluidez en español e inglés. Del trabajo presencial en Ecuador a la colaboración remota con clientes de América y Europa.',
    stats: [
      { value: '3', label: 'continentes' },
      { value: '2', label: 'idiomas de trabajo' },
      { value: 'GMT-5', label: 'base en Quito, Ecuador' },
    ],
    locationsHeading: 'Dónde he colaborado',
    locations: [
      { name: 'Ecuador', tag: 'local' },
      { name: 'Latinoamérica', tag: 'remoto' },
      { name: 'Estados Unidos', tag: 'remoto' },
      { name: 'Europa', tag: 'remoto' },
    ],
    languagesHeading: 'Idiomas',
    languages: [
      { language: 'Español', level: 'Nativo', percent: 100 },
      { language: 'Inglés', level: 'Intermedio · B1', percent: 55 },
    ],
    teamHeading: 'En equipos globales',
    teamItems: [
      'Solapamiento horario con América (EST/PST) y Europa (CET)',
      'Flujo remoto y asíncrono, con dailies y demos en inglés',
      'Documentación y code reviews bilingües (ES/EN)',
      'Adaptación a equipos multiculturales y husos distintos',
    ],
  },
  projects: {
    kicker: 'destacados',
    heading: 'Proyectos',
    items: [
      { category: 'FINTECH', title: 'Banca móvil KMP', description: 'App bancaria multiplataforma con OTP, biometría facial (FacePhi) y cumplimiento de políticas de las stores, con CI/CD en Azure.', tech: ['Kotlin Multiplatform', 'iOS', 'Android', 'Azure'] },
      { category: 'IoT', title: 'Audax · Tuya IoT', description: 'Integración de dispositivos Tuya en una app React Native con un microservicio en Go y pipelines de despliegue móvil optimizados.', tech: ['React Native', 'Go', 'IoT', 'CI/CD'] },
      { category: 'TELECOM', title: 'Smartisp OLT', description: 'Sistema de monitoreo de fibra óptica en tiempo real con dashboards en vivo, control remoto de equipos y telemetría de baja latencia.', tech: ['React', 'SNMP', 'Microservicios'] },
      { category: 'E-COMMERCE', title: 'Plataforma Enterprise', description: '15+ microservicios escalables en AWS con integraciones de pagos y partners, soportando 1000+ usuarios concurrentes.', tech: ['AWS', 'Terraform', 'Kubernetes', 'Node.js'] },
      { category: 'AR/3D', title: 'AR Commerce', description: 'Experiencias de Realidad Aumentada con Unity que digitalizaron catálogos comerciales y triplicaron el engagement de clientes.', tech: ['Unity', 'ARKit', 'ARCore'] },
    ],
  },
  testimonials: {
    kicker: 'recomendaciones',
    heading: 'Lo que dicen de mi trabajo',
    blurb: 'Recomendaciones de líderes técnicos y clientes con quienes he colaborado.',
    linkedinUrl: 'https://www.linkedin.com/in/luis-alberto-de-la-torre-duran-752569141/details/recommendations/',
    items: [
      { name: 'Juan Cruz Cuello', photoUrl: '/images/testimonials/juan-cruz-cuello.jpg', role: 'SSR Software Engineer · NaranjaX', quote: 'Luis es un excelente profesional y compañero. Cuando dejamos de compartir equipo miré hacia atrás y me dejó muy contento todo lo que él había crecido como ingeniero y todo lo que yo había aprendido de él. Sin dudas espero que en un futuro nos crucemos nuevamente.' },
      { name: 'Roberth Borges', photoUrl: '/images/testimonials/roberth-borges.jpg', role: 'Engineering Manager · Tech Lead', quote: 'Tuve la oportunidad de trabajar con Luis durante un par de años. Es una persona extremadamente proactiva, comprometida con alcanzar las metas del equipo, y siempre cuenta con una excelente actitud y energía positiva que aportan mucho valor a un excelente ambiente laboral. Luis es técnicamente muy sólido, con una gran experiencia en JavaScript, arquitecturas de microservicios y orientadas a eventos.' },
      { name: 'Manuel Yaffe', photoUrl: '/images/testimonials/manuel-yaffe.jpg', role: 'Project Management · Cencosud', quote: 'Tuve el placer de trabajar con Luis en Cencosud y siempre me impresionó su habilidad técnica y su capacidad para investigar soluciones complejas. Su dominio de diversas tecnologías le permite entregar resultados de alta calidad dentro de plazos ajustados. Además, es un excelente colaborador, siempre dispuesto a ayudar y compartir conocimientos con el equipo.' },
      { name: 'Jorge Ramírez', photoUrl: '/images/testimonials/jorge-ramirez.jpg', role: 'Head of Product · Banca Digital', quote: 'Tuve la oportunidad de trabajar con Luis en el proyecto Home Delivery Regional, donde fue clave en la integración del producto con el ecosistema de facturación. Luis destacó por su alto nivel técnico, enfoque en la resolución de problemas y excelente capacidad de trabajo en equipo. Su contribución fue decisiva para el éxito del proyecto.' },
      { name: 'Gerardo Alvarez Muñoz', photoUrl: '/images/testimonials/gerardo-alvarez-munoz.jpg', role: 'Staff Engineer', quote: 'Me complace recomendar a Luis Alberto para cualquier posición de desarrollador. He tenido el placer de trabajar con él en varios proyectos y puedo dar fe de sus habilidades técnicas y profesionales, así como de su resolución de problemas, excelente trabajo en equipo y adaptabilidad. Sería una valiosa incorporación para cualquier equipo de desarrollo.' },
      { name: 'Andrés Juárez', photoUrl: '/images/testimonials/andres-juarez.jpg', role: 'Tech Lead · Arquitectura de Software', quote: 'Luis es un developer con una capacidad de adaptación que resalta, trabaja muy bien en equipo, tiene excelentes skills técnicos y es muy comprometido con su trabajo. Recomiendo trabajar con él por todas estas cualidades profesionales y muchas cualidades personales que tiene.' },
      { name: 'Wil Salas', photoUrl: '/images/testimonials/wil-salas.jpg', role: 'Senior Full Stack Developer', quote: 'Es una persona altamente proactiva y disciplinada en cada tarea que se le asigna. Además, aporta significativamente al rendimiento y cohesión de los equipos en los que colabora. Destaca por su compromiso, integridad y dedicación, siendo un profesional confiable y orientado a resultados.' },
      { name: 'Tom Baran-Martinez', photoUrl: '/images/testimonials/tom-baran-martinez.jpg', role: 'English Speaking Coach', quote: 'Tuve el placer y el honor de ser el coach de inglés de Luis durante 4 meses. En ese tiempo, Luis trabajó duro para conseguir un nuevo empleo en Acid Labs, donde debía —y continúa— hablando inglés regularmente con su equipo y clientes. En mi programa, Luis siempre nos trató a mí, a mi equipo y a sus compañeros con el máximo respeto.' },
      { name: 'John Jiménez', photoUrl: '/images/testimonials/john-jimenez.jpg', role: 'Estratega de Marketing Digital', quote: 'Es un excelente profesional, destaco su responsabilidad y compromiso con cada una de sus actividades. Sabe trabajar en equipo y con muy buenas metodologías que facilitan el cumplimiento de objetivos.' },
      { name: 'Edgar Quiles', photoUrl: '/images/testimonials/edgar-quiles.jpg', role: 'Director of Sales · BeTrep', quote: 'Alberto, quien formó parte de nuestra institución por un año, es una persona con una integridad intachable. Ha demostrado ser un excelente elemento para cualquier equipo del que forma parte: su trabajo siempre destaca entre los mejores y afronta los retos de manera comprometida, responsable y organizada. Sobre todo, es una persona con actitud emprendedora, siempre buscando el crecimiento y la mejora de todos.' },
      { name: 'Andres Diaz', photoUrl: '/images/testimonials/andres-diaz.jpg', role: 'Flutter Developer · Founder de Jobnow', quote: 'Un excelente profesional y persona, una capacidad enorme de aprender y su conocimiento por la tecnología es demasiado amplio.' },
      { name: 'Mauricio Baena Vásquez', photoUrl: '/images/testimonials/mauricio-baena-vasquez.jpg', role: 'Diseñador Gráfico Senior', quote: 'Muy buen elemento, apasionado por su carrera, propositivo y responsable; además es un buen compañero, sabe trabajar en equipo y es muy solidario.' },
    ],
  },
  certifications: {
    kicker: 'formación continua',
    heading: 'Certificaciones',
    items: [
      { name: 'Máster en Arquitectura de Microservicios con Docker', issuer: 'Lite Thinking' },
      { name: 'DevOps con AWS', issuer: 'Smart Data' },
      { name: 'NestJS: Persistencia con MongoDB y TypeORM', issuer: 'Platzi' },
      { name: 'Infraestructura como código en Terraform', issuer: 'Platzi' },
      { name: 'Fundamentos de TypeScript', issuer: 'Platzi' },
      { name: 'Testing con JavaScript', issuer: 'Platzi' },
      { name: 'Angular: Componentes y Servicios', issuer: 'Platzi' },
      { name: 'Material UI con React', issuer: 'Platzi' },
      { name: 'Desarrollo Front-End & JavaScript', issuer: 'Coursera' },
      { name: 'Diplomado en Habilidades Directivas', issuer: 'Newman' },
    ],
  },
  education: {
    kicker: 'academia',
    heading: 'Educación',
    items: [
      { title: 'Maestría en Big Data con mención en IA', institution: 'UNIANDES', period: '2026 — Presente' },
      { title: 'Diplomado en Arquitectura Empresarial Moderna', institution: 'Lite Thinking', period: '2025 — Presente' },
      { title: 'AI Assisted Programming Bootcamp', institution: 'Dojo Coding', period: '2025 — Presente' },
      { title: 'Ingeniería en Sistemas', institution: 'UNIANDES', period: '2014 — 2019' },
    ],
    languagesHeading: 'Idiomas',
    languages: [
      { language: 'Español', level: 'Nativo' },
      { language: 'Inglés', level: 'Avanzado' },
    ],
  },
  collaboration: {
    kicker: 'colaboración',
    heading: 'Modelos para trabajar juntos',
    blurb: 'Elige el formato que mejor encaje con tu proyecto. Todo empieza con una llamada gratuita de 30 min.',
    models: [
      { tag: 'ALCANCE CERRADO', title: 'Proyecto llave en mano', description: 'Ideal para MVPs y productos con alcance definido. Precio fijo por entregable.', features: ['Cotización fija por fases', 'Diseño → desarrollo → despliegue', 'Garantía post-entrega'], cta: 'Cotizar proyecto' },
      { tag: 'MENSUAL', title: 'Retainer / por horas', description: 'Capacidad dedicada continua para evolucionar tu producto mes a mes.', features: ['Bloque de horas flexible', 'Prioridad y disponibilidad', 'Reportes y demos semanales'], cta: 'Reservar cupo', popular: true },
      { tag: 'ESTRATÉGICO', title: 'Tech Lead fraccional', description: 'Lidero tu equipo y arquitectura sin el costo de un full-time senior.', features: ['Arquitectura y estándares', 'Code reviews y mentoría', 'Roadmap técnico'], cta: 'Agendar llamada' },
    ],
  },
  contact: {
    kicker: 'contacto',
    heading: '¿Tienes un proyecto en mente? Hablemos.',
    blurb:
      'Estoy disponible para proyectos freelance y colaboraciones. Cuéntame qué quieres construir y te respondo en menos de 24 horas.',
    emailCta: 'Enviar por email',
    whatsappCta: 'Enviar por WhatsApp',
    email: 'luis.atorred24@gmail.com',
    phone: '+593 97 990 6532',
    whatsapp: '593979906532',
    linkedin: 'https://www.linkedin.com/in/luis-alberto-de-la-torre-duran-752569141/',
    location: 'Quito, Ecuador · GMT-5',
    linkedinLabel: '/luis-alberto-de-la-torre',
    formNameLabel: 'Tu nombre',
    formNamePlaceholder: 'Ej: María Torres',
    formTypeLabel: 'Tipo de proyecto',
    projectTypes: ['Web', 'App móvil', 'AR / Unity', 'Backend', 'Cloud / DevOps', 'IA / ML', 'Consultoría'],
    formBudgetLabel: 'Presupuesto estimado',
    budgets: ['< $2k', '$2k–5k', '$5k–15k', '$15k+', 'A definir'],
    formMessageLabel: 'Cuéntame tu proyecto',
    formMessagePlaceholder: '¿Qué quieres construir? Objetivo, plazos, contexto...',
    formHint: 'Recibirás una confirmación y el detalle llegará directo a mi correo. Respondo en menos de 24 h.',
    formEmailLabel: 'Tu email',
    formEmailPlaceholder: 'nombre@correo.com',
    stepProjectLabel: 'Proyecto',
    stepScheduleLabel: 'Agenda',
    nextCta: 'Elegir día y hora →',
    backCta: '← Volver',
    confirmCta: 'Confirmar y enviar',
    slotsHeading: 'Horarios disponibles',
    slotsFreeSuffix: 'horarios libres',
    slotsPickDay: 'Selecciona primero un día en el calendario.',
    bannerPickDay: 'Elige un día y una hora para tu llamada gratuita de 30 min.',
    bannerPickTime: 'Día seleccionado. Ahora elige una hora.',
    bannerScheduled: 'Llamada de 30 min agendada para el {slot}.',
    whatsappAlt: 'o coordinar por WhatsApp',
    successTitle: '¡Solicitud enviada!',
    successBody: 'Recibí tu solicitud para el {slot}. Te confirmo por email en menos de 24 h.',
    successAgain: 'Enviar otra solicitud',
    errorRequired: 'Completa tu nombre y email para continuar.',
    errorSlotTaken: 'Ese horario acaba de ocuparse. Elige otro.',
    errorNetwork: 'No se pudo enviar. Intenta de nuevo o escríbeme por WhatsApp.',
    interestLabel: 'Interesado en',
  },
  footer: {
    copyright: '© 2026 Luis De La Torre Duran',
    tagline: 'Diseñado y desarrollado con precisión.',
  },
};
